In [66]:
list = [num**2 for num in range(1,11) if num%3 == 0]
print(list)

[9, 36, 81]

### Set in python ###

In [67]:
from ctypes import memset


my_empty_set = set()
my_empty_set = set()
my_empty_set.add(1)
my_empty_set.add(2)
my_empty_set.add(3)
my_empty_set.add(2) # This will not be added to the set because sets do not allow duplicate values

print(my_empty_set)
print(type(my_empty_set))

my_set = {1,2,3,4,5,6}
my_set.remove(3)
print(my_set)

pop_number = my_set.pop()
print(pop_number) 

isPresent_3 = 2 in my_set
print(isPresent_3)

{1, 2, 3}
<class 'set'>
{1, 2, 4, 5, 6}
1
True

### methemetical operations on sets ###

In [68]:
set_1 = {1,2,3,4,5}
set_2 = {4,5,6,7,8}
 
union_set = set_1.union(set_2)
print(union_set)

intersection_set = set_1.intersection(set_2)
print(intersection_set)

difference_set = set_1.difference(set_2)

print(difference_set)

set_1.difference_update(set_2)
print(set_1)

{1, 2, 3, 4, 5, 6, 7, 8}
{4, 5}
{1, 2, 3}
{1, 2, 3}

### Symmetric difference ###

In [69]:
set_1 = {1,2,3,4,5}
set_2 = {4,5,6,7,8}
print(set_1.symmetric_difference(set_2))

key = "Hardik"
value = "Dipal"

print(f"\"{key}\" test {value} ansd")

{1, 2, 3, 6, 7, 8}
"Hardik" test Dipal ansd

In [70]:
for i in range(1,11,2):
    print(i)

1
3
5
7
9

## Tupal Example ##

In [71]:
my_tupal= (17,18,19,20,21,22)
my_list = [0,1,2,3,4,5]
##print(my_tupal)
#print(my_tupal[:4])
print(my_tupal[2:4])
print(my_list[::-1])
print(my_list[3:4])
print(my_list*3)

## pack unpack tupal

first,*rest, last  = my_tupal 
print(first)
print(rest) 
print(last)


lst = [[1,2,3,4],[6,7,8,9],[2.5,3,"Hardik",True]]

print("==========================")
      
for item in lst:
    for elements in item:
        print(f"{elements}")

(19, 20)
[5, 4, 3, 2, 1, 0]
[3]
[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]
17
[18, 19, 20, 21]
22
==========================
1
2
3
4
6
7
8
9
2.5
3
Hardik
True

In [72]:
people=[
    {"name":"Hardik","age":25,"city":"Ahmedabad"},
    {"name":"Dipal","age":24,"city":"Surat"},
    {"name":"Rohit","age":26,"city":"Ahmedabad"},
]

print(list(map(lambda person:person['name'],people)))

print(list(filter(lambda person:person['age']>25,people)))

TypeError: 'list' object is not callable

## Numpy ##

In [110]:
import numpy as np



#sliceing of the 2D arry 

my_array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(my_array)

print(my_array[0:2,2:])

print(my_array[1:,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]

# Files #

In [ ]:
list_of_lines = ["This is my first line\n", 
                 "This is my second line\n", 
                 "This is my third line\n"]

# with open("example.txt","a") as file:
#     file.writelines(list_of_lines)

with open("example.txt","r") as file:
    content = file.read()
    print(content.strip())

with open("example.txt","r") as file:
   lines =  file.readlines()
   lines_count = len(lines)
   word_count = sum(len(line.split()) for line in lines)
   character_count = sum(len(line) for line in lines)
    
print(f"Lines: {lines_count}")
print(f"Words: {word_count}")
print(f"Characters: {character_count}")

This is my first line
This is my second line
This is my third line
Lines: 4
Words: 15
Characters: 68

In [ ]:
from abc import ABC, abstractmethod

class Person():
  def __init__(self,name,age,gender):
    self.__name = name
    self._gender = gender
    self.age = age

  def get_name(self):
    return self.__name

class Student(Person):
  def __init__(self,name,age,gender,student_id):
    super().__init__(name,age,gender)
    self.student_id = student_id
 
person_1 = Person("Hardik",25,"Male")
print(person_1.age)
print(person_1.get_name())
#person_1(person_1._gender)

strudent_1 = Student("Hardik",25,"Male",12345)
print(strudent_1._gender)

25
Hardik
Male

In [85]:
def test_function(*args,**kwargs):
    print(args)
    print(kwargs)

test_function(1,2,name="Hardik",age=25)

(1, 2)
{'name': 'Hardik', 'age': 25}

# Pandas #

In [117]:
import pandas as pd

series =pd.Series([1,2,3,4,5])

print(series)
print(type(series))

data = {"a":1,"b":2,"c":3}
series2 = pd.Series(data)
print(series2)

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
a    1
b    2
c    3
dtype: int64

In [120]:
abc = [1,2,3,4,5]
index = ['a','b','c','d','e']
series3 = pd.Series(abc,index=index)
print(series3)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
data = {
    "Name":["Hardik","Dipal","Rohit"],
    "Age":[25,24,26],
    "City":["Ahmedabad","Surat","Pune"]
}

my_first_dataframe = pd.DataFrame(data)
print(my_first_dataframe)

     Name  Age       City
0  Hardik   25  Ahmedabad
1   Dipal   24      Surat
2   Rohit   26       Pune
{'Name': ['Hardik', 'Dipal', 'Rohit'], 'Age': [25, 24, 26], 'City': ['Ahmedabad', 'Surat', 'Pune']}

In [ ]:
# creating dataframe from list of dictionaries
data = [
    {"Name": "Hardik", "Age": 25, "City": "Ahmedabad"},
    {"Name": "Dipal", "Age": 24, "City": "Surat"},
    {"Name": "Rohit", "Age": 26, "City": "Pune"},
    {"Name": "Priya", "Age": 27, "City": "Mumbai"},
    {"Name": "Amit", "Age": 28, "City": "Delhi"},
    {"Name": "Sneha", "Age": 29, "City": "Bangalore"} 
]

my_first_dataframe = pd.DataFrame(data)
my_first_dataframe

     Name  Age       City
0  Hardik   25  Ahmedabad
1   Dipal   24      Surat
2   Rohit   26       Pune

In [ ]:
#Accessing data from dataframe
#my_first_dataframe.loc[1] # Accessing first row using loc
#my_first_dataframe.iloc[1] # Accessing first row using iloc

0    Hardik
1     Dipal
2     Rohit
Name: Name, dtype: object

In [153]:
my_first_dataframe['Salary'] = [50000,60000,55000]
print(my_first_dataframe)

     Name  Age       City  Salary
0  Hardik   25  Ahmedabad   50000
1   Dipal   24      Surat   60000
2   Rohit   26       Pune   55000

In [164]:
#my_first_dataframe.drop('Salary',axis=1,inplace=True)

#my_first_dataframe.drop(0,inplace=True)
my_first_dataframe.describe()

#my_first_dataframe.dtypes

             Age
count   2.000000
mean   25.000000
std     1.414214
min    24.000000
25%    24.500000
50%    25.000000
75%    25.500000
max    26.000000

In [ ]:
from langchain_ollama import OllamaEmbeddings  # Correct: underscore
embaddings = (
    OllamaEmbeddings(model="embeddinggemma")
)

embade_1 = embaddings.embed_documents(
    ["Hello world How are you?"
    ,"write some text Welcome to the course"])

768

In [7]:
import os
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage

load_dotenv()

# langsmith Tracking 
os.environ["LANGCHAIN_API_KEY"] = os.getenv("LANGCHAIN_API_KEY")
os.environ["LANGSMITH_TRACING"] = "true"
os.environ["LANGCHAIN_PROJECT"] = os.getenv("LANGCHAIN_PROJECT")

groq_api_key = os.getenv("GROQ_API_KEY")

groq_gemma2_llm_model = ChatGroq(model="llama-3.1-8b-instant", api_key=groq_api_key)

messages = [
    SystemMessage(content="convert the message from english to gujarati"),
    HumanMessage(content="Hi, How are you ?")
]

print(messages)

response = groq_gemma2_llm_model.invoke(messages)
print(response)

[SystemMessage(content='convert the message from english to gujarati', additional_kwargs={}, response_metadata={}), HumanMessage(content='Hi, How are you ?', additional_kwargs={}, response_metadata={})]
content='નમસ્કાર, તમે શ્રીમંત છો?' additional_kwargs={} response_metadata={'token_usage': {'completion_tokens': 41, 'prompt_tokens': 50, 'total_tokens': 91, 'completion_time': 0.07630138, 'completion_tokens_details': None, 'prompt_time': 0.008280782, 'prompt_tokens_details': None, 'queue_time': 0.091971118, 'total_time': 0.084582162}, 'model_name': 'llama-3.1-8b-instant', 'system_fingerprint': 'fp_4387d3edbb', 'service_tier': 'on_demand', 'finish_reason': 'stop', 'logprobs': None, 'model_provider': 'groq'} id='lc_run--019dba27-4de8-7b93-9406-9f1f2cb38678-0' tool_calls=[] invalid_tool_calls=[] usage_metadata={'input_tokens': 50, 'output_tokens': 41, 'total_tokens': 91}